apiVersion: apps/v1
kind: Deployment
metadata:
  name: cors-simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cors-simple-app
  template:
    metadata:
      labels:
        app: cors-simple-app
    spec:
      containers:
        - name: cors-backend
          image: docker.io/dperique/cors-backend:latest
          ports:
            - containerPort: 7007
        - name: cors-ui
          image: docker.io/dperique/cors-ui:latest
          ports:
            - containerPort: 7007

